"""Pydantic models describing a daily lesson."""
from pydantic import BaseModel, Field


class VocabItem(BaseModel):
    polish: str = Field(description="Dictionary form (infinitive / nominative) or fixed phrase")
    form_in_story: str = Field(description="Exact form as it appears in the story")
    english: str
    part_of_speech: str = ""
    example_pl: str
    example_en: str


class Example(BaseModel):
    polish: str
    english: str


class GrammarRule(BaseModel):
    title: str
    explanation: str
    pattern: str = ""
    examples: list[Example] = Field(default_factory=list)
    story_examples: list[str] = Field(default_factory=list)


class ComprehensionQuestion(BaseModel):
    question_pl: str
    question_en: str
    answer_pl: str


class Lesson(BaseModel):
    # Generated by the LLM
    title_pl: str
    title_en: str
    story_pl: str
    story_en: str
    new_vocabulary: list[VocabItem]
    grammar_rules: list[GrammarRule]
    questions: list[ComprehensionQuestion] = Field(default_factory=list)

    # Filled in by the app (not by the LLM)
    lesson_date: str = ""
    level: str = ""
    topic: str = ""
