"""Pydantic models describing a daily lesson and quiz results."""
from typing import Literal

from pydantic import BaseModel, Field


class VocabItem(BaseModel):
    polish: str = Field(description="Dictionary form (infinitive / nominative) or fixed phrase")
    form_in_story: str = Field(description="Exact form as it appears in the story")
    english: str
    part_of_speech: str = ""
    why_important: str = ""
    example_pl: str
    example_en: str


class Example(BaseModel):
    polish: str
    english: str


class GrammarRule(BaseModel):
    title: str
    explanation: str
    pattern: str = ""
    examples: list[Example] = Field(default_factory=list)
    story_examples: list[str] = Field(default_factory=list)


class QuizQuestion(BaseModel):
    id: int
    type: Literal["multiple_choice", "fill_blank", "open"]
    question: str = Field(description="Question in Polish; fill_blank uses ___ for the gap")
    hint_en: str = ""
    options: list[str] = Field(default_factory=list)        # multiple_choice only
    correct_option: int | None = None                        # multiple_choice only (0-based)
    accepted_answers: list[str] = Field(default_factory=list)  # fill_blank only
    reference_answer: str = ""                               # open only (never shown)


class Lesson(BaseModel):
    # Generated by the LLM
    title_pl: str
    title_en: str
    story_pl: str
    story_en: str
    new_vocabulary: list[VocabItem]
    grammar_rules: list[GrammarRule]
    quiz: list[QuizQuestion] = Field(default_factory=list)

    # Filled in by the app (not by the LLM)
    lesson_date: str = ""
    level: str = ""
    topic: str = ""


class QuestionResult(BaseModel):
    id: int
    score: float          # 0, 0.5 or 1
    feedback: str = ""    # hint only - never contains the correct answer


class QuizAttempt(BaseModel):
    attempt: int
    score: float          # 0.0 - 1.0
    passed: bool
    answers: dict[str, str]
    results: list[QuestionResult]
